---
extends: default

rules:
  # REQUIRED by ansible-lint
  comments-indentation: false

  comments:
    min-spaces-from-content: 1

  braces:
    max-spaces-inside: 1

  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  # Your custom rules
  line-length:
    max: 260

  truthy:
    allowed-values: ["true", "false"]
    check-keys: true
